name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline scripts
        run: |
          node -v
          npm -v
      - name: python
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-window-command:
    runs-on: windows-latest
    needs:  ["run-shell-command"]
    steps:
      - name: Directory Location
        run: Get-Location
      - name: Directory Location Bash
        run: pwd
        shell: bash
